CREATE TABLE profiles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    birth_date  DATE,
    birth_place VARCHAR(120),
    fiscal_code VARCHAR(16),
    email       VARCHAR(254),
    phone       VARCHAR(40),

    CONSTRAINT uk_profiles_fiscal_code UNIQUE (fiscal_code),
    CONSTRAINT ck_profiles_fiscal_code_uppercase CHECK (fiscal_code IS NULL OR fiscal_code = UPPER(fiscal_code)),
    CONSTRAINT ck_profiles_email_lowercase CHECK (email IS NULL OR email = LOWER(email))
);
