CREATE TABLE profile_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    type VARCHAR(40) NOT NULL,
    document_number VARCHAR(100),
    issuing_authority VARCHAR(150),
    issue_date DATE,
    expiration_date DATE,
    notes VARCHAR(1000),
    CONSTRAINT fk_profile_documents_profile FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE,
    CONSTRAINT ck_profile_documents_type CHECK (
        type IN (
            'IDENTITY_CARD',
            'DRIVING_LICENSE',
            'PASSPORT',
            'HEALTH_CARD',
            'OTHER'
        )
    ),
    CONSTRAINT ck_profile_documents_dates CHECK (
        issue_date IS NULL
        OR expiration_date IS NULL
        OR expiration_date >= issue_date
    )
);
CREATE INDEX ix_profile_documents_profile_id ON profile_documents (profile_id);
