CREATE TABLE generated_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    template_id BIGINT NOT NULL,
    generation_type VARCHAR(30) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_generated_documents_profile FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_generated_documents_template FOREIGN KEY (template_id) REFERENCES document_templates (id),
    CONSTRAINT ck_generated_documents_generation_type CHECK (
        generation_type IN ('STANDARD', 'PROFILE_SUMMARY')
    )
);
CREATE INDEX ix_generated_documents_profile_id ON generated_documents (profile_id);
